"""initial caseline schema

Revision ID: 0001
Revises:
Create Date: 2026-09-26 14:29:10.243307
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import caseline.db

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('callers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('callback_number', sa.String(length=32), nullable=True),
    sa.Column('callback_verified', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('preferred_language', sa.String(length=16), nullable=True),
    sa.Column('accessibility_needs', sa.Text(), nullable=True),
    sa.Column('sms_opted_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('registration_id', sa.String(length=64), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_at', caseline.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('jurisdictions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('practice_areas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('languages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('transfer_number', sa.String(length=32), nullable=True),
    sa.Column('referral_email', sa.String(length=320), nullable=True),
    sa.Column('accepting_referrals', sa.Boolean(), nullable=False),
    sa.Column('accepting_live_calls', sa.Boolean(), nullable=False),
    sa.Column('max_open_referrals', sa.Integer(), nullable=False),
    sa.Column('routing_priority', sa.Integer(), nullable=False),
    sa.Column('availability_updated_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key', name='uq_idempotency_scope_key')
    )
    op.create_table('provider_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_event_id', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('received_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('payload_redacted', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_provider_event')
    )
    op.create_table('cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('caller_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('new', 'consent_pending', 'triage_in_progress', 'triage_ready', 'transfer_pending', 'transfer_connected', 'transfer_failed', 'extended_intake', 'referral_pending', 'firm_notified', 'firm_accepted', 'firm_declined', 'human_review', 'no_eligible_firm', 'closed', name='casestatus', native_enum=False, length=40), nullable=False),
    sa.Column('practice_area', sa.String(length=64), nullable=True),
    sa.Column('practice_area_confidence', sa.String(length=16), nullable=True),
    sa.Column('jurisdiction', sa.String(length=64), nullable=True),
    sa.Column('urgent', sa.Boolean(), nullable=False),
    sa.Column('urgency_reason', sa.String(length=64), nullable=True),
    sa.Column('routing_action', sa.String(length=40), nullable=True),
    sa.Column('summary_version', sa.Integer(), nullable=False),
    sa.Column('assigned_operator', sa.String(length=120), nullable=True),
    sa.Column('created_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caller_id'], ['callers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index('ix_cases_status', ['status'], unique=False)

    op.create_table('firm_closures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('closed_on', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'closed_on', name='uq_firm_closure_day')
    )
    op.create_table('firm_hours',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('opens', sa.Time(), nullable=False),
    sa.Column('closes', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_call_id', sa.String(length=128), nullable=False),
    sa.Column('state', sa.Enum('active', 'ended', name='callstate', native_enum=False, length=40), nullable=False),
    sa.Column('started_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ended_at', caseline.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('termination_reason', sa.String(length=40), nullable=True),
    sa.Column('caller_id_number', sa.String(length=32), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_sessions_provider_call_id'), ['provider_call_id'], unique=True)

    op.create_table('case_facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('provenance', sa.Enum('caller_stated', 'caller_confirmed', 'inferred', 'unknown', 'declined', name='factprovenance', native_enum=False, length=40), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'key', name='uq_case_fact_key')
    )
    op.create_table('consent_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('caller_id', sa.Uuid(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('call_session_id', sa.Uuid(), nullable=True),
    sa.Column('subject_firm_slug', sa.String(length=64), nullable=True),
    sa.Column('purpose', sa.Enum('intake', 'recording', 'share_with_selected_firm', 'transfer', 'sms', 'email', name='consentpurpose', native_enum=False, length=40), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('capture_method', sa.String(length=32), nullable=False),
    sa.Column('captured_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['caller_id'], ['callers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_events', schema=None) as batch_op:
        batch_op.create_index('ix_consent_case_purpose', ['case_id', 'purpose'], unique=False)

    op.create_table('referrals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('created', 'transfer_authorized', 'transfer_requested', 'transfer_connected', 'transfer_failed', 'pending_async', 'firm_notified', 'accepted', 'declined', 'expired', name='referralstatus', native_enum=False, length=40), nullable=False),
    sa.Column('share_consent_id', sa.Uuid(), nullable=True),
    sa.Column('selection_rule_version', sa.String(length=32), nullable=False),
    sa.Column('selection_rationale', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('expires_at', caseline.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['share_consent_id'], ['consent_events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index('ix_referrals_firm_id', ['firm_id'], unique=False)
        batch_op.create_index('ix_referrals_status', ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_key', sa.String(length=200), nullable=False),
    sa.Column('job_type', sa.Enum('send_guava_sms', 'send_firm_email', name='jobtype', native_enum=False, length=40), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'email', name='notificationchannel', native_enum=False, length=40), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('referral_id', sa.Uuid(), nullable=True),
    sa.Column('destination', sa.String(length=320), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'submitted', 'blocked', 'failed', name='notificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.String(length=64), nullable=True),
    sa.Column('provider_response_id', sa.String(length=128), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.String(length=200), nullable=True),
    sa.Column('created_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_status', ['status'], unique=False)

    op.create_table('transfer_authorizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('referral_id', sa.Uuid(), nullable=False),
    sa.Column('call_session_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('destination_e164', sa.String(length=32), nullable=False),
    sa.Column('expires_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', caseline.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('transfer_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('referral_id', sa.Uuid(), nullable=False),
    sa.Column('authorization_id', sa.Uuid(), nullable=False),
    sa.Column('provider_transfer_id', sa.String(length=128), nullable=True),
    sa.Column('dial_target', sa.String(length=32), nullable=False),
    sa.Column('state', sa.Enum('requested', 'connected', 'failed', 'no_answer', 'busy', 'unknown', name='transferattemptstate', native_enum=False, length=40), nullable=False),
    sa.Column('attempted_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('connected_at', caseline.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('failed_at', caseline.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('result_source', sa.String(length=32), nullable=True),
    sa.Column('provider_signal', sa.String(length=40), nullable=True),
    sa.Column('created_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['authorization_id'], ['transfer_authorizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authorization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_attempts')
    op.drop_table('transfer_authorizations')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_status')

    op.drop_table('notifications')
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index('ix_referrals_status')
        batch_op.drop_index('ix_referrals_firm_id')

    op.drop_table('referrals')
    with op.batch_alter_table('consent_events', schema=None) as batch_op:
        batch_op.drop_index('ix_consent_case_purpose')

    op.drop_table('consent_events')
    op.drop_table('case_facts')
    with op.batch_alter_table('call_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_sessions_provider_call_id'))

    op.drop_table('call_sessions')
    op.drop_table('firm_hours')
    op.drop_table('firm_closures')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index('ix_cases_status')

    op.drop_table('cases')
    op.drop_table('provider_events')
    op.drop_table('idempotency_keys')
    op.drop_table('firms')
    op.drop_table('callers')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
