"""roles, report versions and encrypted caller PII

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 14:56:09.125201

Autogenerated, then edited: caller PII columns become TEXT holding Fernet ciphertext, and any existing plaintext
rows are encrypted in place with CASELINE_FIELD_ENCRYPTION_KEY (dev key when unset). Downgrade decrypts.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import caseline.db

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

PII_COLUMNS = ("name", "callback_number", "email", "accessibility_needs")


def _fernet():
    from cryptography.fernet import Fernet

    from caseline.config import get_settings
    from caseline.crypto import DEV_FIELD_KEY

    key = get_settings().caseline_field_encryption_key
    return Fernet((key.get_secret_value() if key else DEV_FIELD_KEY).encode())


def _rewrite(transform) -> None:
    conn = op.get_bind()
    rows = conn.execute(sa.text(f"SELECT id, {', '.join(PII_COLUMNS)} FROM callers")).all()
    for row in rows:
        values = {c: (None if v is None else transform(v)) for c, v in zip(PII_COLUMNS, row[1:], strict=True)}
        sets = ", ".join(f"{c} = :{c}" for c in PII_COLUMNS)
        conn.execute(sa.text(f"UPDATE callers SET {sets} WHERE id = :id"), {**values, "id": row[0]})


def upgrade() -> None:
    op.create_table('api_principals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('report_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('referral_id', sa.Uuid(), nullable=False),
    sa.Column('case_revision', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
              nullable=False),
    sa.Column('created_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_id', 'case_revision', name='uq_report_referral_revision')
    )
    with op.batch_alter_table('callers', schema=None) as batch_op:
        batch_op.alter_column('name', existing_type=sa.VARCHAR(length=200), type_=sa.Text(), existing_nullable=True)
        batch_op.alter_column('callback_number', existing_type=sa.VARCHAR(length=32), type_=sa.Text(),
                              existing_nullable=True)
        batch_op.alter_column('email', existing_type=sa.VARCHAR(length=320), type_=sa.Text(), existing_nullable=True)
    f = _fernet()
    _rewrite(lambda v: f.encrypt(v.encode()).decode())


def downgrade() -> None:
    f = _fernet()
    _rewrite(lambda v: f.decrypt(v.encode()).decode())
    with op.batch_alter_table('callers', schema=None) as batch_op:
        batch_op.alter_column('email', existing_type=sa.Text(), type_=sa.VARCHAR(length=320), existing_nullable=True)
        batch_op.alter_column('callback_number', existing_type=sa.Text(), type_=sa.VARCHAR(length=32),
                              existing_nullable=True)
        batch_op.alter_column('name', existing_type=sa.Text(), type_=sa.VARCHAR(length=200), existing_nullable=True)
    op.drop_table('report_versions')
    op.drop_table('api_principals')
