"""live call assessments

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 15:18:47.535088
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import caseline.db

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_session_id', sa.Uuid(), nullable=False),
    sa.Column('facts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('view', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_question', sa.String(length=32), nullable=True),
    sa.Column('asked_question', sa.String(length=32), nullable=True),
    sa.Column('utterances_processed', sa.Integer(), nullable=False),
    sa.Column('created_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', caseline.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_session_id')
    )
    with op.batch_alter_table('call_assessments', schema=None) as batch_op:
        batch_op.create_index('ix_call_assessments_updated_at', ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_assessments', schema=None) as batch_op:
        batch_op.drop_index('ix_call_assessments_updated_at')

    op.drop_table('call_assessments')
    # ### end Alembic commands ###
