"""live transcript

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-26 16:01:11.968029
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import caseline.db

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcript', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_assessments', schema=None) as batch_op:
        batch_op.drop_column('transcript')

    # ### end Alembic commands ###
